# Generated by Django 5.0.7 on 2024-08-16 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0004_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_banned',
            field=models.BooleanField(default=False),
        ),
    ]
