# Generated by Django 5.0.7 on 2024-08-16 17:11

import django.contrib.auth.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0005_user_is_banned'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProxy',
            fields=[
            ],
            options={
                'verbose_name': 'Moderate User',
                'verbose_name_plural': 'Moderate Users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('network.user',),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
